### ISSUE TITLE
UD transformatoram ir problēma ar apvienotām, labotām pieturzīmēm

### ISSUE THREAD

**Issue by lauma** [LUMII-AILab/CorporaTools#37]
Jāapskatās, kas te notiek, laikam tik specifiski labojumi nav bijuši domāti.
```
Processing file "p8464-p2.pml", 17 trees found...
Transforming sentence a-p8464-p2s8 completely failed! Check structure and try again.
java.lang.IllegalArgumentException: Don't know what to do with node "a-p8464-p2s8w16" with form """, w-text "'"", and form_change "union", "spell"
	at lv.ailab.lvtb.universalizer.transformator.morpho.MorphoTransformator.transformCurrentNode(MorphoTransformator.java:193)
	at lv.ailab.lvtb.universalizer.transformator.morpho.MorphoTransformator.transformTokens(MorphoTransformator.java:76)
	at lv.ailab.lvtb.universalizer.transformator.SentenceTransformEngine.transform(SentenceTransformEngine.java:54)
	at lv.ailab.lvtb.universalizer.transformator.SentenceTransformEngine.treeToConll(SentenceTransformEngine.java:107)
	at lv.ailab.lvtb.universalizer.transformator.PmlXmlFileTransformator.readAndTransform(PmlXmlFileTransformator.java:136)
	at lv.ailab.lvtb.universalizer.LvtbToUdUI.main(LvtbToUdUI.java:85)
Transforming sentence a-p8464-p2s8 completely failed! Check structure and try again.
java.lang.NullPointerException: Cannot read field "first" because "result" is null
	at lv.ailab.lvtb.universalizer.transformator.PmlXmlFileTransformator.readAndTransform(PmlXmlFileTransformator.java:137)
	at lv.ailab.lvtb.universalizer.LvtbToUdUI.main(LvtbToUdUI.java:85)
Finished - nothing to write.
```

**Comment by lauma** [comment]
Uz p8464-p2 strādā.
